var staticResourceArr = new Array ("User Start Guide",
"Company Numbers Overview",
"Transferring your phone numbers: How to start a number transfer request",
"Improving Call Quality",
"Adding multiple extensions to your RingCentral online account",
"Configuring the Department rules",
"Customizing the Call Handling & Forwarding feature under User Hours",
"How to send a fax using your email",
"Desktop Phones Frequently Asked Questions",
"How to download the RingCentral mobile app",
"Downloading and installing the RingCentral Softphone on a Windows PC",
"Frequently Asked Questions: Billing",
"RingCentral Business SMS Overview",
"Admin Start Guide",
"Auto-Receptionist Overview",
"Transfering an Existing Number to RingCentral",
"Test your Bandwidth",
"How to add departments",
"Customizing your department's greeting",
"Customizing  your extension's greeting",
"How to Send Faxes Using FaxOut",
"List of tested deskphones with RingCentral",
"Enabling mobile VoIP calling on iOS",
"RingCentral Softphone Minimum Requirements",
"Updating your RingCentral account Credit Card information",
"RingCentral Conference Calling Overview",
"Extension User Overview",
"Users Overview",
"How to Speed up the Number Transfer Process",
"Approved Routers",
"Customizing your Company business hours settings",
"Accessing the advanced Call Handling feature",
"Changing your Security Settings as an Extension User",
"RingCentral CloudFax with Dropbox, Box & Google Drive integration",
"Adding or Purchasing an IP phone or DigitalLine from the online account",
"Enabling mobile VoIP calling on Android",
"Installing the Softphone on a Mac OS X Mountain Lion",
"Checking the minute usage of your RingCentral online account",
"RingCentral App for Salesforce Overview",
"Phones Overview",
"Department Overview",
"Checking the status of your number transfer request",
"Approved Headsets",
"Customizing your Company Hours settings",
"How to make a user extension the manager of a department",
"Customizing the user hours voicemail greeting of your extension",
"Viewing and forwarding a fax from your mobile phone",
"Basic troubleshooting tips for your phones",
"RingCentral Business SMS Overview",
"Assigning the Softphone to a computer",
"Credit Card Authorization Form (CCAF)",
"Presence Overview",
"Tips to a successful number transfer",
"Phones & Numbers Overview",
"RingCentral recommended switches and routers with QoS",
"Customizing your Company Hours greeting",
"How to change the number of your department members",
"Changing the extension's Notification settings",
"Sending scheduled faxes using FaxOut",
"Linksys Telephone Adapter IVR Menus and Commands",
"Sending SMS (text messages) using your RingCentral mobile app for iOS",
"Assigning / Re- Assigning Softphone with Digital Line (Mac)",
"Setting up the International Calling feature as an administrator",
"How to set up an extension's Call Flip options as an Administrator",
"Users Overview",
"Call Handling & Forwarding",
"Tips on how to impove phone call quality",
"Setting up your company hours call setting to connect directly to an extension",
"How to edit a department's information",
"Accessing the advanced Call Handling feature",
"How to change the Faxes sent via Email (FaxOut) Settings option as an Administrator",
"Downloading and installing the RingCentral Softphone on a Windows PC",
"How to send an SMS to your department for Android",
"How to use the Softphone Fax Icon",
"Viewing or printing your billing statement",
"Setting up Call Flip on an extension",
"Department Overview",
"Messages & Notifications Overview",
"Basic troubleshooting tips for your phones",
"Adding or Purchasing an IP phone or DigitalLine from the online account",
"How to edit the department hours messages and notification settings of a department",
"Activating user extensions",
"Editing the Outbound fax settings of an extension",
"Assigning an existing Digital Line to a different extension",
"Conference calling from your RingCentral mobile app",
"Troubleshooting the Softphone",
"Information: Billing Adjustments",
"Automatic Call Recording Frequently Asked Questions",
"Phones & Numbers Overview",
"Screening, Greeting & Hold Music Overview",
"VoIP Connectivity Issues",
"Adding phone numbers to my RingCentral online account",
"Editing the notification settings of a department",
"How to edit your extension's personal information",
"Adding email addresses permitted to send faxes",
"Assigning the Softphone to a computer",
"Call Quality Indicator on mobile app Frequently Asked Questions",
"Changing the fax cover page using the Softphone",
"Information: Billing Date Adjustments for Additional Services",
"Changing the Automatic Call Recording Settings",
"Call Handling & Forwarding",
"Outbound Fax Settings",
"Networking Terms",
"How to change an existing phone number",
"How to enable or disable greetings of a department",
"How to give users adminitrative access and permission to make outgoing calls",
"Supported File Attachments for Faxes",
"Digital Lines - IP Phone User Guides",
"Adding a Personal Contact via iOS",
 "Setting the SoftPhone to use RingOut",
"Changing the service plan of your RingCentral account",
"Enabling/disabling On-Demand Call Recording",
"Screening, Greeting & Hold Music Overview",
"Outbound Caller ID Overview",
"Minimum requirements for RingCentral DigitalLine service",
"Setting up and provisioning existing or third party devices",
"How to set up or edit the on-hold music",
"Resending an extension's welcome email",
"Checklist on how to resolve general fax failures",
"Setting up and provisioning existing or third party devices",
"Adding a Personal Contact via Android",
"Audio Tuning Wizard",
"RingCentral Refund Process",
"Initiating On-Demand Call Recordings",
"Company Numbers Overview",
"Extension User Overview",
"Troubleshooting the Softphone",
"How to access the advanced call handling feature of the auto-receptionist",
"Auto-Receptionist Overview",
"Phones Overview",
"Changing the Operator Extension of your online account",
"Messages & Notifications Overview",
"Outbound Fax Settings",
"Outbound Caller ID Overview");
